# Generated by Django 4.0.5 on 2022-08-05 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0005_alter_perfil_options_alter_perfil_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='web',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
