# Generated by Django 4.0.5 on 2022-08-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('user', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=300)),
                ('enviado', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emisor', to='Chat.usuarios')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receptor', to='Chat.usuarios')),
            ],
            options={
                'ordering': ['-enviado'],
            },
        ),
    ]
