# Generated by Django 4.0.5 on 2022-08-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_rename_mensaje_mensaje_cuerpo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
    ]
