# Generated by Django 4.0.5 on 2022-07-27 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(upload_to='Blog'),
        ),
    ]
