# Generated by Django 4.0.5 on 2022-07-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_subtitulo_alter_blog_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
