# Generated by Django 4.0.5 on 2022-08-06 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0005_alter_blog_options_alter_blog_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Autor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
